spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.niriqiang.blog.domain
  configuration:
    auto-mapping-unknown-column-behavior: warning
    map-underscore-to-camel-case: true
    default-fetch-size: 50
    default-statement-timeout: 10
    use-generated-keys: true

server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    cn.niriqiang.blog.domain: debug

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count:countSql

page:
  size: 3