spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
#    database-platform: cn.niriqiang.blog.util.MySQL5DialectUTF8Util
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

page:
  size: 10

